/* Kit B1 · ejercicios de gramática, uno por guía. [guía, frase, [opciones: la primera es la correcta], explicación] */
const GR = [
 ["be","I ___ from Spain.",["am","is","are"],"<mark>I am</mark> (I'm)."],
 ["be","My sister ___ a nurse.",["is","are","am"],"He / she / it → <mark>is</mark>."],
 ["be","___ you tired?",["Are","Is","Do"],"Preguntas con be: <mark>Are</mark> you...? (sin do)."],
 ["be","They ___ at home. They're at work.",["aren't","isn't","don't"],"They → <mark>aren't</mark>."],
 ["be","I ___ 25 years old.",["am","have","has"],"La edad va con <mark>be</mark>: I'm 25."],
 ["be","Close the window, I'm ___.",["cold","coldness","cold have"],"tener frío = <mark>be cold</mark>."],
 ["be","___ raining outside.",["It's","Is","Are"],"En inglés el sujeto siempre aparece: <mark>It's</mark> raining."],

 ["pronouns","Can you help ___?",["me","I","my"],"Detrás del verbo va el pronombre objeto: <mark>me</mark>."],
 ["pronouns","This is ___ brother, Tom.",["my","me","mine"],"Delante de un sustantivo: <mark>my</mark>."],
 ["pronouns","Is this bag yours? – Yes, it's ___.",["mine","my","me"],"Sin sustantivo detrás: <mark>mine</mark>."],
 ["pronouns","Maria and ___ are friends.",["I","me","my"],"Es sujeto: Maria and <mark>I</mark>."],
 ["pronouns","The dog is eating ___ food.",["its","it's","it"],"<mark>its</mark> = su (de una cosa o animal). it's = it is."],
 ["pronouns","That's ___ car. (el coche de Ana)",["Ana's","Ana","the Ana"],"Posesión con <mark>'s</mark>: Ana's car."],
 ["pronouns","I love my grandparents. I visit ___ every Sunday.",["them","they","their"],"Objeto de they: <mark>them</mark>."],

 ["articles","She's ___ engineer.",["an","a","the"],"Profesión con artículo, y <mark>an</mark> delante de sonido vocal."],
 ["articles","I've got ___ dog and a cat. ___ dog is called Max.",["a / The","the / A","a / A"],"Primera vez <mark>a</mark>, luego ya sabemos cuál: <mark>the</mark>."],
 ["articles","I really like ___.",["cats","the cats","a cats"],"En general, plural sin artículo: I like <mark>cats</mark>."],
 ["articles","We play ___ every Saturday.",["football","the football","a football"],"Deportes sin artículo."],
 ["articles","There are three ___ in my class.",["children","childs","childrens"],"child → <mark>children</mark>."],
 ["articles","Look at ___ birds over there!",["those","this","that"],"Plural y lejos: <mark>those</mark>."],
 ["articles","It takes an ___ to get there.",["hour","hours","our"],"<mark>an hour</mark>: la h no suena."],

 ["numbers","7:45 = It's quarter ___ eight.",["to","past","for"],"Minutos que faltan para la hora: <mark>to</mark>."],
 ["numbers","7:30 = It's half ___ seven.",["past","to","and"],"<mark>half past</mark> seven."],
 ["numbers","My birthday is on the ___ of June.",["third","three","thirdth"],"Fechas con ordinal: <mark>the third</mark>."],
 ["numbers","How do you say 2.5?",["two point five","two comma five","two and five"],"Los decimales se leen con <mark>point</mark>."],
 ["numbers","The film starts ___ 8 o'clock.",["at","in","on"],"<mark>at</mark> + hora."],
 ["numbers","Which month comes after April?",["May","March","June"],"January, February, March, April, <mark>May</mark>..."],

 ["questions","Where ___ you live?",["do","are","does"],"Present simple con you: <mark>do</mark>."],
 ["questions","What time ___ the shop open?",["does","do","is"],"the shop = it → <mark>does</mark>."],
 ["questions","___ did you go on holiday? – To Italy.",["Where","When","Who"],"Respuesta de lugar: <mark>Where</mark>."],
 ["questions","___ brothers have you got?",["How many","How much","How often"],"Contable: <mark>How many</mark>."],
 ["questions","___ is this jacket? – £40.",["How much","How many","What"],"Precio: <mark>How much</mark>."],
 ["questions","What ___ you do yesterday?",["did","do","were"],"Pasado: <mark>did</mark> + verbo base."],
 ["questions","___ do you go to the gym? – Twice a week.",["How often","How long","When"],"Frecuencia: <mark>How often</mark>."],
 ["questions","Do you like coffee? – Yes, I ___.",["do","like","am"],"Respuesta corta con el auxiliar: Yes, I <mark>do</mark>."],

 ["there","___ a supermarket near my house.",["There's","There are","It's"],"Singular: <mark>There's</mark>."],
 ["there","There ___ two bedrooms in the flat.",["are","is","have"],"Plural: <mark>are</mark>."],
 ["there","___ any milk in the fridge?",["Is there","Are there","Has it"],"Milk es incontable: <mark>Is there</mark>."],
 ["there","There ___ a lot of people at the party yesterday.",["were","was","are"],"Pasado plural: <mark>were</mark>."],
 ["there","The cat is ___ the table. (debajo)",["under","on","above"],"<mark>under</mark> = debajo."],
 ["there","The bank is ___ the café and the school.",["between","next","opposite to"],"Entre dos: <mark>between</mark>."],
 ["there","I'm ___ home tonight.",["at","in","on"],"<mark>at home</mark>."],
 ["there","She lives ___ Madrid.",["in","at","on"],"Ciudades: <mark>in</mark>."],

 ["countable","How ___ money have you got?",["much","many","lot"],"Money es incontable: <mark>much</mark>."],
 ["countable","There aren't ___ eggs.",["any","some","much"],"Negativa: <mark>any</mark>."],
 ["countable","Would you like ___ tea?",["some","any","many"],"Ofrecimiento: <mark>some</mark>."],
 ["countable","I've got ___ friends in London. (unos pocos)",["a few","a little","much"],"Contable: <mark>a few</mark>."],
 ["countable","Can I have ___ sugar? (un poco)",["a little","a few","many"],"Incontable: <mark>a little</mark>."],
 ["countable","She gave me some good ___.",["advice","advices","an advice"],"<mark>advice</mark> es incontable."],
 ["countable","We need some new ___ for the living room.",["furniture","furnitures","a furniture"],"<mark>furniture</mark> es incontable."],

 ["can","I ___ swim very well.",["can","can to","cans"],"<mark>can</mark> + verbo sin to, sin -s."],
 ["can","___ you help me, please?",["Can","Do","Are"],"Pedir ayuda: <mark>Can</mark> you...?"],
 ["can","I love ___ to music.",["listening","listen","to listening"],"love + <mark>-ing</mark>."],
 ["can","I'd like ___ a coffee, please.",["—","to","for"],"would like + sustantivo, sin nada en medio: I'd like <mark>a coffee</mark>."],
 ["can","She would like ___ Japan one day.",["to visit","visiting","visit"],"would like + <mark>to</mark> + verbo."],
 ["can","When I was five, I ___ read.",["could","can","could to"],"Pasado de can: <mark>could</mark>."],

 ["past-basic","I ___ at the cinema last night.",["was","were","did"],"I → <mark>was</mark>."],
 ["past-basic","We ___ very tired after the trip.",["were","was","did"],"We → <mark>were</mark>."],
 ["past-basic","She ___ in Paris for two years.",["lived","live","livd"],"-e: solo añade <mark>-d</mark>."],
 ["past-basic","He ___ the bus because it was late.",["stopped","stoped","stopt"],"CVC: se dobla: <mark>stopped</mark>."],
 ["past-basic","I didn't ___ the film.",["like","liked","likes"],"didn't + verbo <mark>base</mark>."],
 ["past-basic","___ you enjoy the party?",["Did","Were","Do"],"Pregunta en pasado: <mark>Did</mark> + verbo."],
 ["past-basic","They ___ at home on Sunday. They were at the beach.",["weren't","didn't","wasn't"],"They → <mark>weren't</mark>."],

 ["used-to","I ___ play the piano when I was a child.",["used to","use to","was used"],"Afirmativa: <mark>used to</mark>."],
 ["used-to","She didn't ___ like vegetables.",["use to","used to","using"],"Negativa: didn't <mark>use to</mark>."],
 ["used-to","Did you ___ live in the countryside?",["use to","used to","usually"],"Pregunta: Did you <mark>use to</mark>...?"],
 ["used-to","We used to ___ to the beach every summer.",["go","going","went"],"used to + verbo <mark>base</mark>."],

 ["comparatives","My brother is ___ than me.",["taller","more tall","tallest"],"Corto: <mark>-er than</mark>."],
 ["comparatives","This book is ___ than the film.",["more interesting","interestinger","most interesting"],"Largo: <mark>more</mark> ... than."],
 ["comparatives","It's the ___ day of the year.",["hottest","hotest","most hot"],"CVC: dobla la consonante: <mark>hottest</mark>."],
 ["comparatives","Today is ___ than yesterday.",["worse","badder","more bad"],"bad → <mark>worse</mark>."],
 ["comparatives","She's the ___ student in the class.",["best","better","goodest"],"good → better → <mark>the best</mark>."],
 ["comparatives","This exercise is ___ than the last one.",["easier","more easy","easyer"],"-y → <mark>-ier</mark>."],
 ["comparatives","He's as tall ___ his father.",["as","than","like"],"<mark>as</mark> ... as."],

 ["modals","You ___ smoke in the hospital. It's forbidden.",["mustn't","don't have to","shouldn't to"],"Prohibido: <mark>mustn't</mark>."],
 ["modals","You ___ come if you don't want to.",["don't have to","mustn't","can't"],"No es necesario: <mark>don't have to</mark>."],
 ["modals","You look ill. You ___ see a doctor.",["should","must to","might"],"Consejo: <mark>should</mark>."],
 ["modals","Take an umbrella. It ___ rain later.",["might","must","should"],"Posibilidad: <mark>might</mark>."],
 ["modals","She ___ wear a uniform at work.",["has to","have to","must to"],"She → <mark>has to</mark>."],
 ["modals","___ I open the window?",["Should","Do should","Shall to"],"Pregunta con modal, sin do: <mark>Should</mark> I...?"],

 ["gerund","I enjoy ___ in the mountains.",["walking","to walk","walk"],"enjoy + <mark>-ing</mark>."],
 ["gerund","We decided ___ at home.",["to stay","staying","stay"],"decide + <mark>to</mark>."],
 ["gerund","I'm interested ___ learning Japanese.",["in","on","to"],"interested <mark>in</mark> + -ing."],
 ["gerund","I went to the supermarket ___ some milk.",["to buy","for buy","for buying"],"Finalidad: <mark>to</mark> + verbo."],
 ["gerund","She's good at ___.",["drawing","draw","to draw"],"Preposición + <mark>-ing</mark>."],
 ["gerund","I want ___ a new phone.",["to buy","buying","buy"],"want + <mark>to</mark>."],
 ["gerund","___ is good for your health.",["Swimming","Swim","To swimming"],"-ing como sujeto: <mark>Swimming</mark>."],
 ["gerund","I'm looking forward to ___ you.",["seeing","see","saw"],"look forward <mark>to + -ing</mark>."],

 ["passive","English ___ in many countries.",["is spoken","speaks","is speak"],"Presente pasivo: is + <mark>participio</mark>."],
 ["passive","This house ___ in 1920.",["was built","built","is build"],"Pasado pasivo: <mark>was built</mark>."],
 ["passive","These phones ___ in Korea.",["are made","is made","make"],"Plural: <mark>are made</mark>."],
 ["passive","The book was written ___ a famous author.",["by","from","for"],"Quién lo hizo: <mark>by</mark>."],
 ["passive","The windows ___ yesterday.",["were cleaned","was cleaned","cleaned"],"Plural pasado: <mark>were</mark> + participio."],

 ["relatives","The woman ___ lives next door is a doctor.",["who","which","where"],"Persona: <mark>who</mark>."],
 ["relatives","This is the phone ___ I bought yesterday.",["which","who","where"],"Cosa: <mark>which</mark>."],
 ["relatives","That's the restaurant ___ we had dinner.",["where","which","who"],"Lugar: <mark>where</mark>."],
 ["relatives","He's the boy ___ bike was stolen.",["whose","who","which"],"Posesión: <mark>whose</mark>."],
 ["relatives","The film ___ we saw was great.",["that","who","where"],"<mark>that</mark> vale para cosas y personas."],

 ["conditionals","If you heat water to 100°C, it ___.",["boils","will boil","would boil"],"Zero conditional: presente + <mark>presente</mark>."],
 ["conditionals","If it ___ tomorrow, we'll stay at home.",["rains","will rain","rained"],"First: if + <mark>presente</mark>."],
 ["conditionals","If I had a car, I ___ drive to work.",["would","will","am"],"Second: if + pasado, <mark>would</mark>."],
 ["conditionals","If I ___ you, I'd study more.",["were","am","will be"],"Consejo: If I <mark>were</mark> you."],
 ["conditionals","I won't go ___ you come with me.",["unless","if","when"],"<mark>unless</mark> = si no."],
 ["conditionals","If she studies, she ___ the exam.",["will pass","passes","would pass"],"First: <mark>will</mark> + verbo."],

 ["reported","«I'm hungry.» → He said he ___ hungry.",["was","is","were"],"am → <mark>was</mark>."],
 ["reported","«I will call you.» → She said she ___ call me.",["would","will","could"],"will → <mark>would</mark>."],
 ["reported","She ___ me that she was busy.",["told","said","asked"],"tell + persona: <mark>told me</mark>."],
 ["reported","He ___ that he liked the film.",["said","told","asked"],"say sin persona: <mark>said</mark> that."],
 ["reported","«Where do you live?» → She asked me where I ___.",["lived","live","do live"],"En preguntas indirectas no hay do y el verbo retrocede: <mark>lived</mark>."],
 ["reported","«I can swim.» → He said he ___ swim.",["could","can","would"],"can → <mark>could</mark>."],

 ["too-enough","This coffee is ___ hot. I can't drink it.",["too","enough","so much"],"Exceso: <mark>too</mark> + adjetivo."],
 ["too-enough","He isn't ___ to drive.",["old enough","enough old","too old"],"Adjetivo + <mark>enough</mark>."],
 ["too-enough","We haven't got ___ chairs.",["enough","too","too many"],"<mark>enough</mark> + sustantivo."],
 ["too-enough","There were ___ people. We couldn't move.",["too many","too much","enough"],"Plural: <mark>too many</mark>."],
 ["too-enough","It was ___ a good day!",["such","so","too"],"<mark>such a</mark> + adjetivo + sustantivo."],
 ["too-enough","The film was ___ boring that I left.",["so","such","too"],"<mark>so</mark> + adjetivo + that."],

 // Preposiciones: of, from, for, on, in, to, at, with, about, between
 ["prepositions","I'd like a cup ___ tea, please.",["of","for","about","from"],"<mark>of</mark>: parte o contenido de algo. Piensa: ¿de qué es?"],
 ["prepositions","She's a friend ___ my sister.",["of","from","to","about"],"<mark>of</mark>: pertenencia. a friend of my sister."],
 ["prepositions","The door ___ the car is broken.",["of","from","about","at"],"<mark>of</mark>: parte de un todo (la puerta del coche)."],
 ["prepositions","This table is made ___ wood.",["of","for","with","about"],"made <mark>of</mark>: el material se sigue viendo (la madera sigue siendo madera)."],
 ["prepositions","What's the name ___ this song?",["of","for","from","about"],"the name <mark>of</mark> = el nombre de."],
 ["prepositions","I'm ___ Spain, but I live in London.",["from","of","to","at"],"<mark>from</mark>: origen. Piensa: ¿de dónde viene?"],
 ["prepositions","Wine is made ___ grapes.",["from","for","with","about"],"made <mark>from</mark>: el material se transforma (las uvas ya no parecen uvas)."],
 ["prepositions","I got an email ___ my teacher.",["from","of","at","between"],"<mark>from</mark>: quién lo envía (el origen)."],
 ["prepositions","The shop is open ___ 9 am to 5 pm.",["from","between","at","for"],"<mark>from</mark> ... to ... = de ... a ... (between va con and)."],
 ["prepositions","Stay away ___ the fire!",["from","of","to","at"],"away <mark>from</mark>: separación, alejarse de algo."],
 ["prepositions","This present is ___ you.",["for","to","of","at"],"<mark>for</mark>: para quién es (beneficiario)."],
 ["prepositions","I've lived here ___ three years.",["for","from","in","at"],"<mark>for</mark> + duración."],
 ["prepositions","We went out ___ dinner.",["for","of","at","with"],"<mark>for</mark>: finalidad. Piensa: ¿para qué?"],
 ["prepositions","Thanks ___ your help!",["for","of","about","to"],"Thanks <mark>for</mark> + lo que agradeces."],
 ["prepositions","I'm waiting ___ the bus.",["for","to","at","of"],"wait <mark>for</mark> = esperar a / esperar algo."],
 ["prepositions","The keys are ___ the table.",["on","in","at","of"],"<mark>on</mark>: encima, tocando la superficie."],
 ["prepositions","See you ___ Monday!",["on","in","at","to"],"<mark>on</mark> + días de la semana."],
 ["prepositions","My birthday is ___ 5th May.",["on","in","at","of"],"<mark>on</mark> + fechas concretas."],
 ["prepositions","There's a picture ___ the wall.",["on","in","at","of"],"<mark>on</mark> the wall: en una superficie."],
 ["prepositions","I saw it ___ TV.",["on","in","at","with"],"<mark>on</mark> TV, on the radio, on the internet."],
 ["prepositions","We're ___ the bus now.",["on","at","to","of"],"<mark>on</mark> the bus / train / plane (transporte público)."],
 ["prepositions","The cat is hiding ___ the box.",["in","at","of","to"],"<mark>in</mark>: dentro de algo cerrado."],
 ["prepositions","I was born ___ 1998.",["in","on","at","for"],"<mark>in</mark> + años."],
 ["prepositions","We go skiing ___ January.",["in","on","at","for"],"<mark>in</mark> + meses (periodos largos)."],
 ["prepositions","Can you say it ___ English?",["in","on","with","of"],"<mark>in</mark> + idiomas: in English, in Spanish."],
 ["prepositions","She lives ___ London.",["in","at","on","to"],"<mark>in</mark> + ciudades y países."],
 ["prepositions","I'll be ready ___ five minutes.",["in","for","at","on"],"<mark>in</mark> five minutes = dentro de cinco minutos."],
 ["prepositions","I go ___ school by bus.",["to","at","in","for"],"<mark>to</mark>: dirección, hacia dónde vas."],
 ["prepositions","Give this letter ___ your mother.",["to","at","of","with"],"give something <mark>to</mark> someone: quién lo recibe."],
 ["prepositions","It's ten ___ nine. (8:50)",["to","for","from","at"],"<mark>to</mark>: minutos que faltan para la hora."],
 ["prepositions","Welcome ___ the party!",["to","at","in","for"],"Welcome <mark>to</mark> + lugar o evento."],
 ["prepositions","Listen ___ me, please!",["to","at","for","with"],"listen <mark>to</mark> someone."],
 ["prepositions","I'm going ___ the cinema tonight.",["to","at","in","for"],"go <mark>to</mark> + lugar (movimiento)."],
 ["prepositions","I'll meet you ___ the station.",["at","on","to","of"],"<mark>at</mark>: un punto concreto donde quedar."],
 ["prepositions","The film starts ___ 8 o'clock.",["at","in","on","for"],"<mark>at</mark> + hora exacta."],
 ["prepositions","She's ___ work right now.",["at","in","on","to"],"<mark>at</mark> work, at home, at school."],
 ["prepositions","I'm not very good ___ maths.",["at","in","on","of"],"good <mark>at</mark> + actividad o asignatura."],
 ["prepositions","Look ___ that bird!",["at","to","for","on"],"look <mark>at</mark> = mirar algo."],
 ["prepositions","We stayed ___ home last night.",["at","in","on","to"],"<mark>at</mark> home (sin the)."],
 ["prepositions","I went to the cinema ___ my friends.",["with","of","to","between"],"<mark>with</mark>: compañía. Piensa: ¿juntos?"],
 ["prepositions","Write your name ___ a pen, not a pencil.",["with","of","from","for"],"<mark>with</mark>: la herramienta que usas."],
 ["prepositions","She's the girl ___ blue eyes.",["with","of","in","from"],"<mark>with</mark>: una característica (la chica de los ojos azules)."],
 ["prepositions","A coffee ___ milk, please.",["with","of","in","for"],"<mark>with</mark> = con."],
 ["prepositions","I agree ___ you.",["with","to","about","for"],"agree <mark>with</mark> someone."],
 ["prepositions","Tell me ___ your holiday.",["about","of","on","for"],"<mark>about</mark>: el tema. Piensa: ¿de qué trata?"],
 ["prepositions","There were ___ 50 people at the party.",["about","between","of","in"],"<mark>about</mark> + número = aproximadamente."],
 ["prepositions","How do you feel ___ your new job?",["about","on","of","with"],"feel <mark>about</mark>: opiniones y sentimientos."],
 ["prepositions","What's the film ___?",["about","of","at","to"],"be <mark>about</mark> = tratar de."],
 ["prepositions","Don't worry ___ it.",["about","of","on","for"],"worry <mark>about</mark> = preocuparse por."],
 ["prepositions","Sit ___ Ana and Tom.",["between","of","from","about"],"<mark>between</mark>: entre dos personas o cosas."],
 ["prepositions","The shop is closed ___ 2 and 4 pm.",["between","from","at","in"],"<mark>between</mark> ... and ...: entre dos límites."],
 ["prepositions","Share the pizza ___ the two of you.",["between","of","from","for"],"<mark>between</mark>: repartido entre dos."],
 ["prepositions","This is a secret ___ you and me.",["between","of","from","at"],"<mark>between</mark> you and me = entre tú y yo."],
 ["prepositions","What's the difference ___ «in» and «on»?",["between","of","with","about"],"the difference <mark>between</mark> A and B."],
 ["prepositions","I'm afraid ___ spiders.",["of","from","about","at"],"afraid <mark>of</mark> = tener miedo de."],
 ["prepositions","It's very kind ___ you.",["of","for","to","with"],"It's kind <mark>of</mark> you = qué amable por tu parte."],
 ["prepositions","A lot ___ people came to the concert.",["of","from","with","for"],"a lot <mark>of</mark> = mucho, muchos."],
 ["prepositions","My phone is different ___ yours.",["from","of","with","at"],"different <mark>from</mark> = diferente de."],
 ["prepositions","I borrowed this book ___ the library.",["from","of","with","to"],"borrow something <mark>from</mark>: de dónde viene."],
 ["prepositions","She's famous ___ her songs.",["for","of","about","with"],"famous <mark>for</mark> = famoso por."],
 ["prepositions","Can you help me look ___ my keys? I've lost them.",["for","at","to","on"],"look <mark>for</mark> = buscar. look at = mirar."],
 ["prepositions","It depends ___ the weather.",["on","of","from","about"],"depend <mark>on</mark> = depender de (¡no «of»!)."],
 ["prepositions","I'm ___ holiday next week.",["on","in","at","for"],"<mark>on</mark> holiday = de vacaciones."],
 ["prepositions","We met ___ Christmas Day.",["on","in","at","for"],"<mark>on</mark> + un día concreto."],
 ["prepositions","I'm interested ___ photography.",["in","on","about","for"],"interested <mark>in</mark> = interesado en."],
 ["prepositions","She's ___ the kitchen.",["in","on","at","to"],"<mark>in</mark>: dentro de una habitación."],
 ["prepositions","I always study ___ the morning.",["in","on","at","for"],"<mark>in</mark> the morning / afternoon / evening."],
 ["prepositions","This bag belongs ___ me.",["to","of","for","with"],"belong <mark>to</mark> = pertenecer a."],
 ["prepositions","He's married ___ Laura.",["to","with","of","for"],"married <mark>to</mark> = casado con (¡no «with»!)."],
 ["prepositions","We arrived ___ the airport late.",["at","to","for","on"],"arrive <mark>at</mark> + lugar concreto. Nunca «arrive to»."],
 ["prepositions","___ night I like reading.",["At","In","On","For"],"<mark>at</mark> night (excepción: in the morning, pero at night)."],
 ["prepositions","She studies ___ university in Madrid.",["at","on","to","of"],"<mark>at</mark> university / at school."],
 ["prepositions","He's angry ___ his brother.",["with","of","for","on"],"angry <mark>with</mark> someone."],
 ["prepositions","I live ___ my parents.",["with","of","for","from"],"<mark>with</mark> = con (compañía)."],
 ["prepositions","What's wrong ___ you?",["with","of","for","about"],"What's wrong <mark>with</mark>...? = ¿Qué le pasa a...?"],
 ["prepositions","I'm thinking ___ you.",["about","at","for","to"],"think <mark>about</mark> = pensar en."],
 ["prepositions","We talked ___ the film for hours.",["about","of","at","for"],"talk <mark>about</mark> = hablar de."],
 ["prepositions","There's a café ___ the bank and the school.",["between","from","of","with"],"<mark>between</mark> A and B = entre A y B."],
 ["prepositions","You have to choose ___ the red one and the blue one.",["between","of","at","about"],"choose <mark>between</mark> dos opciones."],

 // in / on / at: tiempo y lugar
 ["prep-iot","The party is ___ Saturday night.",["on","in","at"],"<mark>on</mark> + día + parte del día: on Saturday night."],
 ["prep-iot","I'll see you ___ the weekend.",["at","in","on"],"<mark>at</mark> the weekend (inglés británico, el del examen)."],
 ["prep-iot","Shops close early ___ Christmas Eve.",["on","in","at"],"<mark>on</mark> + un día concreto."],
 ["prep-iot","We met ___ 2019.",["in","on","at"],"<mark>in</mark> + año."],
 ["prep-iot","The meeting is ___ 10:30.",["at","in","on"],"<mark>at</mark> + hora."],
 ["prep-iot","It's very cold here ___ winter.",["in","on","at"],"<mark>in</mark> + estación del año."],
 ["prep-iot","I was born ___ 12th March.",["on","in","at"],"<mark>on</mark> + fecha."],
 ["prep-iot","Meet me ___ the bus stop.",["at","in","on"],"<mark>at</mark> + punto concreto."],
 ["prep-iot","There's a spider ___ the ceiling!",["on","in","at"],"<mark>on</mark> + superficie (también el techo)."],
 ["prep-iot","She lives ___ the third floor.",["on","in","at"],"<mark>on</mark> the first / second / third floor."],
 ["prep-iot","I read it ___ a magazine.",["in","on","at"],"<mark>in</mark> a magazine / a book / a newspaper."],
 ["prep-iot","We arrived ___ Paris at midnight.",["in","at","on"],"arrive <mark>in</mark> + ciudad o país."],
 ["prep-iot","I'll call you ___ lunchtime.",["at","in","on"],"<mark>at</mark> lunchtime / at dinnertime."],
 ["prep-iot","The concert is ___ the evening.",["in","on","at"],"<mark>in</mark> the evening."],
 ["prep-iot","There's a lot of snow ___ the mountains.",["in","on","at"],"<mark>in</mark> the mountains."],
 ["prep-iot","___ the moment I'm very busy.",["At","In","On"],"<mark>at</mark> the moment = en este momento."],
 ["prep-iot","___ the end of the film, everyone cried.",["At","In","On"],"<mark>at</mark> the end of + algo. (In the end = al final, finalmente)."],

 // Verbo o adjetivo + preposición
 ["prep-dep","We're waiting ___ the results.",["for","to","at","of"],"wait <mark>for</mark>."],
 ["prep-dep","Are you afraid ___ the dark?",["of","from","about","at"],"afraid <mark>of</mark>."],
 ["prep-dep","She's very proud ___ her son.",["of","for","about","with"],"proud <mark>of</mark> = orgulloso de."],
 ["prep-dep","I'm tired ___ this rainy weather.",["of","at","with","about"],"tired <mark>of</mark> = harto de."],
 ["prep-dep","This town is famous ___ its cheese.",["for","of","about","by"],"famous <mark>for</mark>."],
 ["prep-dep","It depends ___ you.",["on","of","from","about"],"depend <mark>on</mark>."],
 ["prep-dep","I'm worried ___ my exam.",["about","for","of","with"],"worried <mark>about</mark>."],
 ["prep-dep","Don't laugh ___ me!",["at","of","about","with"],"laugh <mark>at</mark> someone = reírse de alguien."],
 ["prep-dep","Can I talk ___ you for a minute?",["to","at","for","of"],"talk <mark>to</mark> someone."],
 ["prep-dep","She's really good ___ languages.",["at","in","on","of"],"good <mark>at</mark>."],
 ["prep-dep","I'm looking forward ___ the holidays.",["to","for","at","of"],"look forward <mark>to</mark> = tener ganas de."],
 ["prep-dep","He apologised ___ being late.",["for","of","about","to"],"apologise <mark>for</mark> = pedir perdón por."],
 ["prep-dep","Please pay ___ the tickets at the door.",["for","to","at","of"],"pay <mark>for</mark> something."],
 ["prep-dep","I'm bored ___ this game.",["with","at","for","to"],"bored <mark>with</mark> (en inglés informal también «bored of»)."],
 ["prep-dep","She's married ___ an actor.",["to","with","of","for"],"married <mark>to</mark>."],
 ["prep-dep","I'm sorry ___ the noise.",["about","of","with","at"],"sorry <mark>about</mark> something (también «sorry for»)."],
 ["prep-dep","Who does this bag belong ___?",["to","of","for","with"],"belong <mark>to</mark>."],
 ["prep-dep","Take care ___ yourself!",["of","about","for","with"],"take care <mark>of</mark> = cuidar de."],
 ["prep-dep","She's very keen ___ tennis.",["on","in","of","at"],"keen <mark>on</mark> = muy aficionado a."],
 ["prep-dep","Who is responsible ___ this project?",["for","of","about","on"],"responsible <mark>for</mark> = responsable de."],

 // Encuentra el error
 ["prep-err","«I'm good in English.» → I'm good ___ English.",["at","on","of","for"],"good <mark>at</mark>, nunca «good in»."],
 ["prep-err","«She's married with a doctor.» → She's married ___ a doctor.",["to","of","for","at"],"married <mark>to</mark>, nunca «married with»."],
 ["prep-err","«It depends of the weather.» → It depends ___ the weather.",["on","from","in","at"],"depend <mark>on</mark>, nunca «depend of»."],
 ["prep-err","«I'm interested on music.» → I'm interested ___ music.",["in","at","of","for"],"interested <mark>in</mark>."],
 ["prep-err","«We arrived to London at 9.» → We arrived ___ London at 9.",["in","on","of","for"],"arrive <mark>in</mark> + ciudad, arrive at + lugar. Nunca «arrive to»."],
 ["prep-err","«Listen me!» → Listen ___ me!",["to","at","for","with"],"listen <mark>to</mark> someone."],
 ["prep-err","«I'm waiting you.» → I'm waiting ___ you.",["for","to","at","of"],"wait <mark>for</mark> someone."],
 ["prep-err","«See you in Monday.» → See you ___ Monday.",["on","at","for","to"],"<mark>on</mark> + días."],
 ["prep-err","«I can't sleep in the night.» → I can't sleep ___ night.",["at","on","for","of"],"<mark>at</mark> night."],
 ["prep-err","«I've lived here since three years.» → I've lived here ___ three years.",["for","from","in","on"],"<mark>for</mark> + duración. since + momento."],
 ["prep-err","«He's angry of me.» → He's angry ___ me.",["with","for","on","from"],"angry <mark>with</mark> someone."],
 ["prep-err","«Let's discuss about the plan.» → Let's discuss ___ the plan.",["—","on","of","for"],"<mark>discuss</mark> no lleva preposición: discuss the plan."],
 ["prep-err","«She entered in the room.» → She entered ___ the room.",["—","to","at","on"],"<mark>enter</mark> no lleva preposición: enter the room."],
 ["prep-err","«It's different of mine.» → It's different ___ mine.",["from","with","at","for"],"different <mark>from</mark>."]
];

// Textos con huecos de preposiciones, en formato Reading Part 5 y Part 6
const PREP_TEXTS = [
 { id:"prep-text1", title:"Preposiciones: texto con huecos 1", sub:"Un texto de opción múltiple y otro para escribir. Unos 10 minutos.",
   parts:[
    { type:"cloze", title:"Elige la preposición (como Reading Part 5)", intro:"Elige la opción correcta para cada hueco.",
      text:`<h4>A weekend in Bath</h4><p>Last weekend I went (1) Bath (2) my cousin. We arrived (3) Saturday morning and stayed (4) a small hotel (5) the station and the park. (6) the afternoon we visited the Roman Baths. The guide told us a lot (7) the history of the city. We came back home (8) Sunday evening, tired but happy.</p>`,
      items:[
       { opts:["to","at","in","for"], a:0, why:"go <b>to</b> + lugar (movimiento)." },
       { opts:["with","of","for","about"], a:0, why:"<b>with</b> = con (compañía)." },
       { opts:["on","in","at","for"], a:0, why:"<b>on</b> + día: on Saturday morning." },
       { opts:["in","on","to","of"], a:0, why:"stay <b>in</b> a hotel (dentro)." },
       { opts:["between","from","with","of"], a:0, why:"<b>between</b> the station <b>and</b> the park." },
       { opts:["In","On","At","For"], a:0, why:"<b>In</b> the afternoon." },
       { opts:["about","of","for","on"], a:0, why:"tell someone <b>about</b> something." },
       { opts:["on","in","at","for"], a:0, why:"<b>on</b> Sunday evening." }
      ]},
    { type:"open", title:"Escribe la preposición (como Reading Part 6)", intro:"Escribe UNA preposición en cada hueco.",
      text:`<p>Dear Sara,</p><p>Thanks (1) your message! I'm writing (2) you from my new flat. It's (3) the fourth floor and it has a great view (4) the park. I've lived here (5) two weeks with a friend (6) work. Come and visit me (7) the weekend!</p><p>Love, Marta</p>`,
      answers:[["for"],["to"],["on"],["of"],["for"],["from","at"],["at","on"]],
      why:["Thanks <b>for</b>.","write <b>to</b> someone.","<b>on</b> the fourth floor.","a view <b>of</b> something.","<b>for</b> + duración.","a friend <b>from</b> work (también «at work»).","<b>at</b> the weekend (en inglés americano, on the weekend)."] }
   ]},
 { id:"prep-text2", title:"Preposiciones: texto con huecos 2", sub:"Un texto de opción múltiple y otro para escribir. Unos 10 minutos.",
   parts:[
    { type:"cloze", title:"Elige la preposición (como Reading Part 5)", intro:"Elige la opción correcta para cada hueco.",
      text:`<h4>My friend Tom</h4><p>My best friend Tom is crazy (1) football. He plays (2) a local team and he is very good (3) scoring goals. Every Saturday (4) 10 o'clock, I go (5) the stadium to watch him. Last month his team won the cup, and there was a photo of them (6) the newspaper. Tom was really proud (7) himself. He says he wants to play (8) England one day.</p>`,
      items:[
       { opts:["about","of","on","at"], a:0, why:"crazy <b>about</b> = loco por." },
       { opts:["for","to","of","at"], a:0, why:"play <b>for</b> a team = jugar en un equipo." },
       { opts:["at","in","on","of"], a:0, why:"good <b>at</b> + -ing." },
       { opts:["at","on","in","for"], a:0, why:"<b>at</b> + hora." },
       { opts:["to","at","in","for"], a:0, why:"go <b>to</b> + lugar." },
       { opts:["in","on","at","of"], a:0, why:"<b>in</b> the newspaper." },
       { opts:["of","for","about","with"], a:0, why:"proud <b>of</b>." },
       { opts:["for","to","with","in"], a:0, why:"play <b>for</b> England = jugar con la selección de Inglaterra." }
      ]},
    { type:"open", title:"Escribe la preposición (como Reading Part 6)", intro:"Escribe UNA preposición en cada hueco.",
      text:`<p>Hi Leo,</p><p>I'm writing to tell you (1) my new job. I work (2) a hospital (3) the city centre. I start (4) 7 am, so I get up very early. I'm really happy (5) it because I love helping people. My boss is very nice (6) me.</p><p>Speak soon, Ana</p>`,
      answers:[["about"],["in","at"],["in"],["at"],["with","about"],["to"]],
      why:["tell someone <b>about</b> something.","work <b>in</b> / <b>at</b> a hospital: las dos valen.","<b>in</b> the city centre.","<b>at</b> + hora.","happy <b>with</b> / <b>about</b> something.","nice <b>to</b> someone."] }
   ]}
];
