/* Kit B1 · vocabulario por temas del B1 Preliminary. Formato: "inglés=español|..." */
const TOPICS_RAW = [
 ["family","Familia y personas","mother=madre|father=padre|parents=padres|brother=hermano|sister=hermana|son=hijo|daughter=hija|grandparents=abuelos|uncle=tío|aunt=tía|cousin=primo, prima|husband=marido|wife=esposa|twins=gemelos|boyfriend=novio|neighbour=vecino"],
 ["describe","Describir a alguien","tall=alto|short=bajo|slim=delgado|curly hair=pelo rizado|straight hair=pelo liso|beard=barba|friendly=simpático|kind=amable|funny=gracioso|shy=tímido|lazy=vago|hard-working=trabajador|clever=listo|polite=educado|rude=maleducado|generous=generoso"],
 ["feelings","Sentimientos","happy=feliz|sad=triste|angry=enfadado|worried=preocupado|nervous=nervioso|bored=aburrido|excited=emocionado|tired=cansado|scared=asustado|surprised=sorprendido|proud=orgulloso|embarrassed=avergonzado|disappointed=decepcionado|relaxed=relajado|jealous=celoso|lonely=solo (sentirse)"],
 ["house","Casa","kitchen=cocina|bedroom=dormitorio|bathroom=baño|living room=salón|garden=jardín|stairs=escaleras|floor=suelo, planta|wall=pared|roof=tejado|fridge=nevera|cooker=cocina (el aparato)|sofa=sofá|shelf=estantería|washing machine=lavadora|flat=piso|rent=alquiler"],
 ["routine","Rutina diaria","wake up=despertarse|get up=levantarse|have a shower=ducharse|get dressed=vestirse|have breakfast=desayunar|have lunch=comer|have dinner=cenar|brush your teeth=lavarse los dientes|go to bed=acostarse|do the housework=hacer las tareas|do the shopping=hacer la compra|take the bus=coger el autobús|go to work=ir a trabajar|come home=volver a casa|relax=descansar|fall asleep=dormirse"],
 ["food","Comida y bebida","bread=pan|cheese=queso|meat=carne|chicken=pollo|fish=pescado|vegetables=verduras|fruit=fruta|rice=arroz|eggs=huevos|butter=mantequilla|sugar=azúcar|salt=sal|juice=zumo|water=agua|a bottle of=una botella de|a piece of cake=un trozo de tarta|spicy=picante|delicious=delicioso|menu=carta|bill=cuenta (restaurante)"],
 ["clothes","Ropa y compras","shirt=camisa|T-shirt=camiseta|trousers=pantalones|jeans=vaqueros|skirt=falda|dress=vestido|jacket=chaqueta|coat=abrigo|shoes=zapatos|trainers=zapatillas deportivas|hat=sombrero, gorro|size=talla|try on=probarse|price=precio|cheap=barato|expensive=caro|sale=rebajas|receipt=recibo, tique|change=cambio (dinero)|cash=efectivo"],
 ["town","La ciudad","library=biblioteca|bookshop=librería|chemist's=farmacia|post office=oficina de correos|square=plaza|bridge=puente|traffic lights=semáforo|pavement=acera|crossroads=cruce|museum=museo|town hall=ayuntamiento|police station=comisaría|shopping centre=centro comercial|car park=aparcamiento|turn left=gira a la izquierda|go straight on=sigue recto"],
 ["travel","Viajes y transporte","trip=viaje, excursión|journey=trayecto|flight=vuelo|passport=pasaporte|luggage=equipaje|ticket=billete|return ticket=billete de ida y vuelta|platform=andén|timetable=horario|delay=retraso|departure=salida|arrival=llegada|book=reservar|abroad=en el extranjero|sightseeing=turismo, ver monumentos|campsite=camping|miss the bus=perder el autobús|get on=subir (bus, tren)"],
 ["weather","El tiempo","sunny=soleado|cloudy=nublado|windy=ventoso|foggy=con niebla|rain=lluvia|snow=nieve|storm=tormenta|thunder=trueno|lightning=relámpago|hot=caluroso|warm=templado|cool=fresco|freezing=helado|temperature=temperatura|weather forecast=previsión del tiempo|wet=mojado|dry=seco|degrees=grados"],
 ["health","Salud y cuerpo","head=cabeza|stomach=estómago|back=espalda|arm=brazo|leg=pierna|knee=rodilla|throat=garganta|a cold=un resfriado|a cough=tos|a temperature=fiebre|headache=dolor de cabeza|toothache=dolor de muelas|hurt=doler, hacerse daño|medicine=medicina|appointment=cita|ill=enfermo|get better=mejorar|healthy=sano"],
 ["sport","Deporte y tiempo libre","team=equipo|match=partido|player=jugador|win=ganar|lose=perder|score=marcar, resultado|beat=ganar a (un rival)|coach=entrenador|gym=gimnasio|go swimming=ir a nadar|go cycling=ir en bici|play chess=jugar al ajedrez|hobby=afición|collect=coleccionar|concert=concierto|exhibition=exposición|free time=tiempo libre|join a club=apuntarse a un club"],
 ["work","Trabajo y estudios","job=trabajo, empleo|work=trabajo (incontable)|boss=jefe|colleague=compañero de trabajo|salary=sueldo|earn=ganar (dinero)|apply for=solicitar|interview=entrevista|part-time=a tiempo parcial|full-time=a jornada completa|degree=título universitario|subject=asignatura|timetable=horario|homework=deberes|pass an exam=aprobar|fail an exam=suspender|take an exam=hacer un examen|teacher=profesor"],
 ["tech","Tecnología y medios","laptop=portátil|screen=pantalla|keyboard=teclado|download=descargar|upload=subir|website=página web|password=contraseña|charger=cargador|battery=batería|app=aplicación|send a message=mandar un mensaje|post=publicar|follow=seguir|news=noticias|article=artículo|advert=anuncio|channel=canal|online=en internet"],
 ["nature","Naturaleza y medio ambiente","environment=medio ambiente|pollution=contaminación|recycle=reciclar|rubbish=basura|plastic=plástico|energy=energía|save=ahorrar, salvar|waste=desperdiciar|forest=bosque|river=río|lake=lago|coast=costa|hill=colina|field=campo (terreno)|countryside=el campo|wildlife=fauna|protect=proteger|climate change=cambio climático"],
 ["verbs","Verbos imprescindibles","borrow=pedir prestado|lend=prestar|bring=traer|carry=llevar (en brazos)|choose=elegir|decide=decidir|explain=explicar|forget=olvidar|remember=acordarse|remind=recordar (a alguien)|agree=estar de acuerdo|arrive=llegar|leave=irse, dejar|spend=gastar, pasar (tiempo)|wait for=esperar a|look for=buscar|find=encontrar|hope=esperar (desear)"]
];
TOPICS_RAW.push(
 ["jobs","Profesiones","doctor=médico|nurse=enfermero|lawyer=abogado|engineer=ingeniero|farmer=granjero|firefighter=bombero|police officer=policía|waiter=camarero|chef=cocinero (jefe)|shop assistant=dependiente|mechanic=mecánico|builder=albañil|plumber=fontanero|hairdresser=peluquero|journalist=periodista|pilot=piloto|dentist=dentista|receptionist=recepcionista"],
 ["animals","Animales","dog=perro|cat=gato|horse=caballo|cow=vaca|sheep=oveja|pig=cerdo|hen=gallina|rabbit=conejo|mouse=ratón|bird=pájaro|fish=pez|snake=serpiente|bear=oso|monkey=mono|lion=león|elephant=elefante|insect=insecto|bee=abeja"],
 ["body","El cuerpo","face=cara|eye=ojo|ear=oreja|nose=nariz|mouth=boca|tooth=diente|hair=pelo|neck=cuello|shoulder=hombro|hand=mano|finger=dedo (de la mano)|foot=pie|toe=dedo del pie|chest=pecho|skin=piel|heart=corazón|brain=cerebro|blood=sangre"],
 ["school","Colegio y estudios","classroom=aula|whiteboard=pizarra|pencil=lápiz|rubber=goma de borrar|ruler=regla|notebook=cuaderno|dictionary=diccionario|maths=matemáticas|history=historia|geography=geografía|science=ciencias|term=trimestre|break=recreo|mark=nota (de un examen)|uniform=uniforme|head teacher=director (de colegio)|revise=repasar|learn by heart=aprender de memoria"],
 ["money","Dinero y banco","coin=moneda|note=billete (dinero)|credit card=tarjeta de crédito|cash machine=cajero automático|bank account=cuenta bancaria|pocket money=paga|wallet=cartera|purse=monedero|bill=factura|cost=costar|afford=permitirse (pagar)|owe=deber (dinero)|pay back=devolver (dinero)|discount=descuento|refund=reembolso|save money=ahorrar dinero|spend money=gastar dinero|price=precio"],
 ["entertainment","Cine, música y ocio","film=película|actor=actor|director=director (de cine)|audience=público|scene=escena|ticket office=taquilla|band=grupo (de música)|singer=cantante|song=canción|stage=escenario|show=espectáculo|comedy=comedia|horror film=película de miedo|documentary=documental|cartoon=dibujos animados|novel=novela|character=personaje|festival=festival"],
 ["hotel","Hotel y vacaciones","reception=recepción|single room=habitación individual|double room=habitación doble|key=llave|lift=ascensor|towel=toalla|swimming pool=piscina|suitcase=maleta|guidebook=guía (libro)|tourist=turista|souvenir=recuerdo (objeto)|map=mapa|sunglasses=gafas de sol|suncream=crema solar|check out=dejar el hotel|full board=pensión completa|view=vista|reservation=reserva"],
 ["cooking","Cocinar y la cocina","boil=hervir|fry=freír|bake=hornear|roast=asar|cut=cortar|chop=picar|mix=mezclar|peel=pelar|frying pan=sartén|saucepan=cazo|oven=horno|plate=plato|bowl=cuenco|fork=tenedor|knife=cuchillo|spoon=cuchara|glass=vaso|recipe=receta"],
 ["adjectives","Adjetivos opuestos","big=grande|small=pequeño|long=largo|heavy=pesado|light=ligero|easy=fácil|difficult=difícil|early=temprano|late=tarde|empty=vacío|full=lleno|loud=ruidoso|quiet=tranquilo, silencioso|safe=seguro|dangerous=peligroso|clean=limpio|dirty=sucio|strong=fuerte|weak=débil|rich=rico|poor=pobre"],
 ["communication","Teléfono y comunicación","phone number=número de teléfono|message=mensaje|text=mandar un mensaje (SMS)|voicemail=buzón de voz|hang up=colgar|answer the phone=coger el teléfono|busy=ocupado (la línea)|signal=cobertura|email address=dirección de correo|attachment=archivo adjunto|reply=responder|letter=carta|stamp=sello|envelope=sobre|postcard=postal|address=dirección (de casa)"],
 ["countries","Países y nacionalidades","Spain=España|Spanish=español|England=Inglaterra|English=inglés|the UK=el Reino Unido|British=británico|France=Francia|French=francés|Germany=Alemania|German=alemán|Italy=Italia|Italian=italiano|Portuguese=portugués|the USA=Estados Unidos|American=estadounidense|Chinese=chino|Japan=Japón|Japanese=japonés|Greece=Grecia|Greek=griego"],
 ["emergencies","Emergencias y problemas","accident=accidente|ambulance=ambulancia|fire=incendio|help!=¡socorro!|thief=ladrón|burglar=ladrón (de casas)|injured=herido|lost=perdido|emergency=emergencia|broken=roto|witness=testigo|crash=choque|first aid=primeros auxilios|rescue=rescatar|dangerous=peligroso|fall over=caerse|bleed=sangrar"],
 ["timewords","Palabras de tiempo","yesterday=ayer|tomorrow=mañana (día)|the day after tomorrow=pasado mañana|the day before yesterday=anteayer|weekend=fin de semana|fortnight=quincena|century=siglo|decade=década|midnight=medianoche|midday=mediodía|soon=pronto|later=más tarde|often=a menudo|sometimes=a veces|rarely=casi nunca|always=siempre|never=nunca|ago=hace (tiempo)"],
 ["shopping","De compras","supermarket=supermercado|queue=cola|trolley=carro|basket=cesta|checkout=caja|customer=cliente|cashier=cajero|bargain=ganga|brand=marca|open=abierto|closed=cerrado|changing room=probador|go shopping=ir de compras|second-hand=de segunda mano|deliver=entregar|order=pedir, encargar|online shopping=compras por internet|return=devolver (un producto)"],
 ["chores","Tareas de casa","do the washing=poner la lavadora|do the ironing=planchar|do the washing-up=fregar los platos|make the bed=hacer la cama|hoover=pasar la aspiradora|tidy up=ordenar|dust=quitar el polvo|take out the rubbish=sacar la basura|feed the cat=dar de comer al gato|water the plants=regar las plantas|cook dinner=hacer la cena|lay the table=poner la mesa|clean the windows=limpiar las ventanas|sweep=barrer|mop the floor=fregar el suelo"]
);
// Temas agrupados para los menús
const TOPIC_GROUPS = [
 {title:"Personas", ids:["family","describe","feelings","body","jobs","countries"]},
 {title:"Casa y vida diaria", ids:["house","routine","chores","food","cooking","timewords"]},
 {title:"Ciudad, viajes y compras", ids:["town","travel","hotel","clothes","shopping","money"]},
 {title:"Estudios, trabajo y tecnología", ids:["work","school","tech","communication"]},
 {title:"Salud, naturaleza y problemas", ids:["health","weather","nature","animals","emergencies"]},
 {title:"Ocio", ids:["sport","entertainment"]},
 {title:"Palabras útiles", ids:["verbs","adjectives"]}
];
const TOPICS = TOPICS_RAW.map(([id, name, s]) => ({ id, name, words: s.split("|").map(p => p.split("=")) }));

// Tarjetas de preposiciones. Formato: "inglés=español|..."
const PREP_CARDS_RAW = [
 ["prep-dep","Verbo o adjetivo + preposición","afraid of=tener miedo de|proud of=orgulloso de|tired of=harto de|good at=bueno en|interested in=interesado en|famous for=famoso por|different from=diferente de|married to=casado con|depend on=depender de|listen to=escuchar a|wait for=esperar a|look at=mirar|look for=buscar|look after=cuidar|agree with=estar de acuerdo con|worry about=preocuparse por|talk about=hablar de|belong to=pertenecer a|angry with=enfadado con|keen on=aficionado a|responsible for=responsable de|pay for=pagar (algo)|apologise for=pedir perdón por|laugh at=reírse de|arrive in=llegar a (ciudad, país)|arrive at=llegar a (un lugar concreto)|think about=pensar en|look forward to=tener ganas de"],
 ["prep-iot","In, on, at: expresiones","at night=por la noche|in the morning=por la mañana|on Monday=el lunes|at the weekend=el fin de semana|in July=en julio|on 5th May=el 5 de mayo|at 8 o'clock=a las 8|at Christmas=en Navidad|on Christmas Day=el día de Navidad|in summer=en verano|at home=en casa|at work=en el trabajo|in bed=en la cama|on the bus=en el autobús|in the car=en el coche|on the wall=en la pared|in the photo=en la foto|on TV=en la tele|on the first floor=en el primer piso|at the station=en la estación|in the kitchen=en la cocina|on holiday=de vacaciones|at the moment=en este momento|on time=puntual|in time=a tiempo (con margen)|at the end of=al final de"]
];
const PREP_CARDS = PREP_CARDS_RAW.map(([id, name, s]) => ({ id, name, words: s.split("|").map(p => p.split("=")) }));
