/* Kit B1 · vocabulario por temas del B1 Preliminary. Formato: "inglés=español|..." */
const TOPICS_RAW = [
 ["family","Familia y personas","mother=madre|father=padre|parents=padres|brother=hermano|sister=hermana|son=hijo|daughter=hija|grandparents=abuelos|uncle=tío|aunt=tía|cousin=primo, prima|husband=marido|wife=esposa|twins=gemelos|boyfriend=novio|neighbour=vecino"],
 ["describe","Describir a alguien","tall=alto|short=bajo|slim=delgado|curly hair=pelo rizado|straight hair=pelo liso|beard=barba|friendly=simpático|kind=amable|funny=gracioso|shy=tímido|lazy=vago|hard-working=trabajador|clever=listo|polite=educado|rude=maleducado|generous=generoso"],
 ["feelings","Sentimientos","happy=feliz|sad=triste|angry=enfadado|worried=preocupado|nervous=nervioso|bored=aburrido|excited=emocionado|tired=cansado|scared=asustado|surprised=sorprendido|proud=orgulloso|embarrassed=avergonzado|disappointed=decepcionado|relaxed=relajado|jealous=celoso|lonely=solo (sentirse)"],
 ["house","Casa","kitchen=cocina|bedroom=dormitorio|bathroom=baño|living room=salón|garden=jardín|stairs=escaleras|floor=suelo, planta|wall=pared|roof=tejado|fridge=nevera|cooker=cocina (el aparato)|sofa=sofá|shelf=estantería|washing machine=lavadora|flat=piso|rent=alquiler"],
 ["routine","Rutina diaria","wake up=despertarse|get up=levantarse|have a shower=ducharse|get dressed=vestirse|have breakfast=desayunar|have lunch=comer|have dinner=cenar|brush your teeth=lavarse los dientes|go to bed=acostarse|do the housework=hacer las tareas|do the shopping=hacer la compra|take the bus=coger el autobús|go to work=ir a trabajar|come home=volver a casa|relax=descansar|fall asleep=dormirse"],
 ["food","Comida y bebida","bread=pan|cheese=queso|meat=carne|chicken=pollo|fish=pescado|vegetables=verduras|fruit=fruta|rice=arroz|eggs=huevos|butter=mantequilla|sugar=azúcar|salt=sal|juice=zumo|water=agua|a bottle of=una botella de|a piece of cake=un trozo de tarta|spicy=picante|delicious=delicioso|menu=carta|bill=cuenta (restaurante)"],
 ["clothes","Ropa y compras","shirt=camisa|T-shirt=camiseta|trousers=pantalones|jeans=vaqueros|skirt=falda|dress=vestido|jacket=chaqueta|coat=abrigo|shoes=zapatos|trainers=zapatillas deportivas|hat=sombrero, gorro|size=talla|try on=probarse|price=precio|cheap=barato|expensive=caro|sale=rebajas|receipt=recibo, tique|change=cambio (dinero)|cash=efectivo"],
 ["town","La ciudad","library=biblioteca|bookshop=librería|chemist's=farmacia|post office=oficina de correos|square=plaza|bridge=puente|traffic lights=semáforo|pavement=acera|crossroads=cruce|museum=museo|town hall=ayuntamiento|police station=comisaría|shopping centre=centro comercial|car park=aparcamiento|turn left=gira a la izquierda|go straight on=sigue recto"],
 ["travel","Viajes y transporte","trip=viaje, excursión|journey=trayecto|flight=vuelo|passport=pasaporte|luggage=equipaje|ticket=billete|return ticket=billete de ida y vuelta|platform=andén|timetable=horario|delay=retraso|departure=salida|arrival=llegada|book=reservar|abroad=en el extranjero|sightseeing=turismo, ver monumentos|campsite=camping|miss the bus=perder el autobús|get on=subir (bus, tren)"],
 ["weather","El tiempo","sunny=soleado|cloudy=nublado|windy=ventoso|foggy=con niebla|rain=lluvia|snow=nieve|storm=tormenta|thunder=trueno|lightning=relámpago|hot=caluroso|warm=templado|cool=fresco|freezing=helado|temperature=temperatura|weather forecast=previsión del tiempo|wet=mojado|dry=seco|degrees=grados"],
 ["health","Salud y cuerpo","head=cabeza|stomach=estómago|back=espalda|arm=brazo|leg=pierna|knee=rodilla|throat=garganta|a cold=un resfriado|a cough=tos|a temperature=fiebre|headache=dolor de cabeza|toothache=dolor de muelas|hurt=doler, hacerse daño|medicine=medicina|appointment=cita|ill=enfermo|get better=mejorar|healthy=sano"],
 ["sport","Deporte y tiempo libre","team=equipo|match=partido|player=jugador|win=ganar|lose=perder|score=marcar, resultado|beat=ganar a (un rival)|coach=entrenador|gym=gimnasio|go swimming=ir a nadar|go cycling=ir en bici|play chess=jugar al ajedrez|hobby=afición|collect=coleccionar|concert=concierto|exhibition=exposición|free time=tiempo libre|join a club=apuntarse a un club"],
 ["work","Trabajo y estudios","job=trabajo, empleo|work=trabajo (incontable)|boss=jefe|colleague=compañero de trabajo|salary=sueldo|earn=ganar (dinero)|apply for=solicitar|interview=entrevista|part-time=a tiempo parcial|full-time=a jornada completa|degree=título universitario|subject=asignatura|timetable=horario|homework=deberes|pass an exam=aprobar|fail an exam=suspender|take an exam=hacer un examen|teacher=profesor"],
 ["tech","Tecnología y medios","laptop=portátil|screen=pantalla|keyboard=teclado|download=descargar|upload=subir|website=página web|password=contraseña|charger=cargador|battery=batería|app=aplicación|send a message=mandar un mensaje|post=publicar|follow=seguir|news=noticias|article=artículo|advert=anuncio|channel=canal|online=en internet"],
 ["nature","Naturaleza y medio ambiente","environment=medio ambiente|pollution=contaminación|recycle=reciclar|rubbish=basura|plastic=plástico|energy=energía|save=ahorrar, salvar|waste=desperdiciar|forest=bosque|river=río|lake=lago|coast=costa|hill=colina|field=campo (terreno)|countryside=el campo|wildlife=fauna|protect=proteger|climate change=cambio climático"],
 ["verbs","Verbos imprescindibles","borrow=pedir prestado|lend=prestar|bring=traer|carry=llevar (en brazos)|choose=elegir|decide=decidir|explain=explicar|forget=olvidar|remember=acordarse|remind=recordar (a alguien)|agree=estar de acuerdo|arrive=llegar|leave=irse, dejar|spend=gastar, pasar (tiempo)|wait for=esperar a|look for=buscar|find=encontrar|hope=esperar (desear)"]
];
const TOPICS = TOPICS_RAW.map(([id, name, s]) => ({ id, name, words: s.split("|").map(p => p.split("=")) }));
