/* Kit B1 · plan de 10 semanas desde cero y recursos externos gratuitos.
   Tareas: ["g", guía] ["q", test] ["c", tarjetas] ["x", simulacro] ["r", recurso] ["t", tarea libre] */

// Recursos externos: solo enlaces, con su fuente. Nada de su contenido se copia aquí.
const RESOURCES = [
 { id:"cam-prep", cat:"Examen oficial", name:"B1 Preliminary: preparación", by:"Cambridge English",
   url:"https://www.cambridgeenglish.org/exams-and-tests/preliminary/preparation/",
   what:"Exámenes de muestra oficiales de Reading, Listening y Writing, con soluciones, y vídeos de Speaking con comentarios del examinador." },
 { id:"cam-yt", cat:"Examen oficial", name:"Canal de YouTube", by:"Cambridge English",
   url:"https://www.youtube.com/@CambridgeEnglishTV",
   what:"Vídeos oficiales, entre ellos exámenes de Speaking reales grabados." },
 { id:"yt-speaking", cat:"Examen oficial", name:"Buscar «B1 Preliminary speaking test» en YouTube", by:"YouTube",
   url:"https://www.youtube.com/results?search_query=B1+Preliminary+speaking+test",
   what:"Para ver cómo es el Speaking por dentro. Mejor si el vídeo es del canal oficial de Cambridge." },
 { id:"wi", cat:"Writing", name:"Write & Improve", by:"Cambridge English",
   url:"https://writeandimprove.com/",
   what:"Pega tus emails e historias y te da una corrección automática con tu nivel estimado. Gratis." },
 { id:"engexam", cat:"Práctica del examen", name:"Tests de Reading y Listening PET", by:"EngExam.info",
   url:"https://engexam.info/b1-preliminary-pet-practice-tests/reading/",
   what:"Tests de práctica del B1 Preliminary con explicaciones." },
 { id:"bc-a2", cat:"Gramática", name:"Gramática A1–A2", by:"British Council · LearnEnglish",
   url:"https://learnenglish.britishcouncil.org/free-resources/grammar/a1-a2",
   what:"Explicaciones y ejercicios gratis de nivel básico." },
 { id:"bc-b1", cat:"Gramática", name:"Gramática B1–B2", by:"British Council · LearnEnglish",
   url:"https://learnenglish.britishcouncil.org/free-resources/grammar/b1-b2",
   what:"Explicaciones y ejercicios gratis de nivel intermedio." },
 { id:"bbc-6min", cat:"Listening", name:"6 Minute English", by:"BBC Learning English",
   url:"https://www.bbc.co.uk/learningenglish/english/features/6-minute-english",
   what:"Episodios de 6 minutos con vocabulario y transcripción. Perfecto para el metro." },
 { id:"bbc-yt", cat:"Listening", name:"Canal de YouTube", by:"BBC Learning English",
   url:"https://www.youtube.com/@bbclearningenglish",
   what:"Vídeos cortos de gramática, vocabulario y pronunciación." },
 { id:"lucy", cat:"Listening", name:"English with Lucy", by:"YouTube",
   url:"https://www.youtube.com/@EnglishwithLucy",
   what:"Pronunciación y vocabulario en inglés británico, el acento del examen." },
 { id:"dict", cat:"Diccionario", name:"Diccionario inglés-español", by:"Cambridge Dictionary",
   url:"https://dictionary.cambridge.org/es/diccionario/ingles-espanol/",
   what:"Con audio de pronunciación británica y americana." }
];

const PLAN = [
 { title:"Arranque: lo básico", goal:"Presentarte, hablar de tu familia y saber cómo es el examen.",
   tasks:[["g","exam"],["g","be"],["q","gr-be"],["g","pronouns"],["q","gr-pronouns"],["g","articles"],["q","gr-articles"],["g","numbers"],["q","gr-numbers"],
          ["c","tp-family"],["c","tp-describe"],["t","Escribe 5 frases sobre ti: nombre, edad, de dónde eres, trabajo y familia."],["r","bbc-yt"]] },
 { title:"Presente, preguntas y lugares", goal:"Hablar de tu rutina, tu casa y tu ciudad, y hacer preguntas.",
   tasks:[["g","ps-pc"],["g","questions"],["q","gr-questions"],["g","there"],["q","gr-there"],["g","prepositions"],["q","prep-exam"],["c","tp-routine"],["c","tp-house"],["c","tp-town"],
          ["t","Describe tu rutina en 8 frases con always, usually, sometimes y never."],["r","bc-a2"]] },
 { title:"Ahora vs siempre, cantidades y gustos", goal:"Diferenciar presente simple y continuo, y hablar de comida, ropa y aficiones.",
   tasks:[["q","tn"],["g","countable"],["q","gr-countable"],["g","can"],["q","gr-can"],["c","tp-food"],["c","tp-clothes"],["c","tp-sport"],
          ["t","Grábate 1 minuto hablando de lo que te gusta hacer (like, love, hate + -ing)."],["r","cam-prep"]] },
 { title:"El pasado", goal:"Contar lo que hiciste. Los verbos irregulares más frecuentes, de memoria.",
   tasks:[["g","past-basic"],["q","gr-past-basic"],["g","irr"],["c","iv"],["q","iv"],["g","time"],["q","te"],["c","tp-travel"],
          ["t","Escribe un email de 100 palabras a un amigo contando tu último fin de semana."],["r","wi"]] },
 { title:"Contar historias", goal:"Past continuous, conectores y comparativos: lo que necesitas para la historia del Writing.",
   tasks:[["g","past-cont"],["q","pc"],["g","linkers"],["g","comparatives"],["q","gr-comparatives"],["c","tp-weather"],["c","tp-feelings"],["g","writing"],
          ["t","Escribe una historia de 100 palabras que empiece: «It was a cold winter night...»"],["r","bbc-6min"]] },
 { title:"Futuro, phrasal verbs y Speaking", goal:"Hablar de planes y hacer tu primer simulacro.",
   tasks:[["g","future"],["g","particles"],["c","pv"],["q","pv"],["c","tp-work"],["g","speaking"],["r","yt-speaking"],
          ["t","Speaking Part 1: contesta en voz alta 10 preguntas sobre ti, 2 frases por respuesta."],["x","sim1"]] },
 { title:"Present perfect y modales", goal:"Experiencias, obligaciones y consejos. El salto de A2 a B1.",
   tasks:[["g","past-pp"],["q","tn"],["g","modals"],["q","gr-modals"],["c","tp-health"],["c","tp-tech"],["q","vo-Confusiones"],
          ["t","Escribe 6 frases sobre experiencias con ever, never, already y yet."],["r","engexam"]] },
 { title:"Gramática B1 (I)", goal:"Used to, -ing o to, pasiva y relativos.",
   tasks:[["g","used-to"],["q","gr-used-to"],["g","gerund"],["q","gr-gerund"],["g","passive"],["q","gr-passive"],["g","relatives"],["q","gr-relatives"],
          ["c","tp-nature"],["c","tp-verbs"],["t","Artículo de 100 palabras: «Is technology good for young people?»"],["r","wi"]] },
 { title:"Gramática B1 (II) y vocabulario trampa", goal:"Condicionales, estilo indirecto y las palabras que más fallan los hispanohablantes.",
   tasks:[["g","conditionals"],["q","gr-conditionals"],["g","reported"],["q","gr-reported"],["g","too-enough"],["q","gr-too-enough"],
          ["q","vo-Falsos amigos"],["q","vo-Make / Do"],["q","vo-Collocations"],["x","sim2"],["r","cam-prep"]] },
 { title:"Repaso final", goal:"Simulacros, fallos a cero y confianza para el día del examen.",
   tasks:[["t","Repasa la pestaña Fallos hasta dejarla vacía."],["q","mix"],["x","sim1"],["x","sim2"],["r","cam-prep"],
          ["t","Haz un examen oficial de muestra completo, con el tiempo real."],["t","Speaking: describe 3 fotos de tu móvil durante 1 minuto cada una."],
          ["g","exam"],["t","El día antes: descansa, prepara el DNI y comprueba la hora y el lugar del examen."]] }
];
